License dataset
UdL-EPS-SoftArch/mydata-api pull request #24
Opened 2017-03-04 11:59 UTC by sergiplca

2017-03-06 18:10 UTC, rogargon requested changes

2017-03-06 18:10 UTC, rogargon commented on src/main/java/cat/udl/eps/entsoftarch/repository/ClosedLicenseRepository.java
> +    List <ClosedLicense> findByText(@Param("text") String text, @Param("price") double price);
If the idea is to find by both text and price the method name should be findByTextAndPrice. More details: https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-keywords

If just find by text or price, the other method parameter should be omitted

2017-03-06 18:10 UTC, rogargon commented on src/main/java/cat/udl/eps/entsoftarch/repository/ClosedLicenseRepository.java
> +@RepositoryRestResource(collectionResourceRel="closedlicenses", path="closedlicenses")
Better to keep the default collectionResourceRel "closedLicense" to follow the same approach through the whole API

2017-03-06 18:10 UTC, rogargon commented on src/test/resources/features/RegisterLicense.feature
> +    When I register a closed license with text "text" and price 10
What about ownership of the closed license? The idea is that it is associated to user "owner". Is it so?

2017-03-06 18:23 UTC, victorserrate commented on src/test/resources/features/RegisterLicense.feature
> +    When I register a closed license with text "text" and price 10
Hello Roberto, I don't understand what are you saying.  We replicated the same scenarios for both License types. What do you want exactly? Only the closed license will have owner or both?

2017-03-06 18:43 UTC, rogargon commented on src/test/resources/features/RegisterLicense.feature
> +    When I register a closed license with text "text" and price 10
This is a scenario about closed license, but the same applies to open if they also have a field owner. Like in the register dataset feature, the idea is that one a user creates a license, the user becomes the owner. The scenario does not check this is true

2017-03-07 08:21 UTC, rogargon approved these changes

2017-03-07 08:23 UTC, merged