Feature/search tag by name starting with(issue#19)
UdL-EPS-SoftArch/mydata-api pull request #37
Opened 2017-03-09 14:47 UTC by joanj94

2017-03-09 16:03 UTC, rogargon requested changes

2017-03-09 16:03 UTC, rogargon commented on src/main/java/cat/udl/eps/entsoftarch/repository/TagRepository.java
> +    List<Tag> findByNameContaining(@Param("name") String name);
The feature is about looking for tags starting with some text. The implementation is about containing...

2017-03-13 14:30 UTC, joanj94 commented on src/main/java/cat/udl/eps/entsoftarch/repository/TagRepository.java
> +    List<Tag> findByNameContaining(@Param("name") String name);
Added new functions and scenarios to check it

2017-03-13 15:15 UTC, rogargon approved these changes

2017-03-13 15:15 UTC, merged